Internal Server Error: /ss
"GET /ss HTTP/1.1" 500 145
Internal Server Error: /ss
"GET /ss HTTP/1.1" 500 145
Internal Server Error: /ss
"GET /ss HTTP/1.1" 500 145
Internal Server Error: /aa
"GET /aa HTTP/1.1" 500 145
Internal Server Error: /zzz
"GET /zzz HTTP/1.1" 500 145
Internal Server Error: /static/css/tailwind.output.css
"GET /static/css/tailwind.output.css HTTP/1.1" 500 145
Internal Server Error: /zz
"GET /zz HTTP/1.1" 500 145
Internal Server Error: /static/css/tailwind.output.css
"GET /static/css/tailwind.output.css HTTP/1.1" 500 145
Internal Server Error: /dd
"GET /dd HTTP/1.1" 500 145
Internal Server Error: /static/css/tailwind.output.css
"GET /static/css/tailwind.output.css HTTP/1.1" 500 145
Internal Server Error: /fff
"GET /fff HTTP/1.1" 500 145
Internal Server Error: /static/css/tailwind.output.css
"GET /static/css/tailwind.output.css HTTP/1.1" 500 145
Internal Server Error: /static/css/tailwind.output.css
"GET /static/css/tailwind.output.css HTTP/1.1" 500 145
Internal Server Error: /static/css/tailwind.output.css
"GET /static/css/tailwind.output.css HTTP/1.1" 500 145
Internal Server Error: /static/css/tailwind.output.css
"GET /static/css/tailwind.output.css HTTP/1.1" 500 145
Internal Server Error: /dd
"GET /dd HTTP/1.1" 500 145
Internal Server Error: /static/css/tailwind.output.css
"GET /static/css/tailwind.output.css HTTP/1.1" 500 145
Internal Server Error: /static/css/tailwind.output.css
"GET /static/css/tailwind.output.css HTTP/1.1" 500 145
Internal Server Error: /static/css/tailwind.output.css
"GET /static/css/tailwind.output.css HTTP/1.1" 500 145
Internal Server Error: /static/css/tailwind.output.css
"GET /static/css/tailwind.output.css HTTP/1.1" 500 145
Internal Server Error: /static/css/tailwind.output.css
"GET /static/css/tailwind.output.css HTTP/1.1" 500 145
Internal Server Error: /static/img/body.webp
"GET /static/img/body.webp HTTP/1.1" 500 145
Internal Server Error: /static/css/tailwind.output.css
"GET /static/css/tailwind.output.css HTTP/1.1" 500 145
Internal Server Error: /static/img/body.webp
"GET /static/img/body.webp HTTP/1.1" 500 145
Internal Server Error: /static/css/tailwind.output.css
"GET /static/css/tailwind.output.css HTTP/1.1" 500 145
Internal Server Error: /staticfiles/css/tailwind.output.css
"GET /staticfiles/css/tailwind.output.css HTTP/1.1" 500 145
Internal Server Error: /static/img/body.webp
"GET /static/img/body.webp HTTP/1.1" 500 145
Internal Server Error: /staticfiles/css/tailwind.output.css
"GET /staticfiles/css/tailwind.output.css HTTP/1.1" 500 145
Internal Server Error: /static/img/body.webp
"GET /static/img/body.webp HTTP/1.1" 500 145
Internal Server Error: /staticfiles/css/tailwind.output.css
"GET /staticfiles/css/tailwind.output.css HTTP/1.1" 500 145
Internal Server Error: /static/img/body.webp
"GET /static/img/body.webp HTTP/1.1" 500 145
Internal Server Error: /static/css/tailwind.output.css
"GET /static/css/tailwind.output.css HTTP/1.1" 500 145
Internal Server Error: /static/img/body.webp
"GET /static/img/body.webp HTTP/1.1" 500 145
Internal Server Error: /static/css/tailwind.output.css
"GET /static/css/tailwind.output.css HTTP/1.1" 500 145
Internal Server Error: /static/img/body.webp
"GET /static/img/body.webp HTTP/1.1" 500 145
Internal Server Error: /static/css/tailwind.output.css
"GET /static/css/tailwind.output.css HTTP/1.1" 500 145
Internal Server Error: /static/img/body.webp
"GET /static/img/body.webp HTTP/1.1" 500 145
Internal Server Error: /static/css/tailwind.output.css
"GET /static/css/tailwind.output.css HTTP/1.1" 500 145
Internal Server Error: /static/css/tailwind.output.css
"GET /static/css/tailwind.output.css HTTP/1.1" 500 145
Internal Server Error: /static/img/body.webp
"GET /static/img/body.webp HTTP/1.1" 500 145
Internal Server Error: /static/css/tailwind.output.css
"GET /static/css/tailwind.output.css HTTP/1.1" 500 145
Internal Server Error: /static/img/body.webp
"GET /static/img/body.webp HTTP/1.1" 500 145
Internal Server Error: /static/css/tailwind.output.css
"GET /static/css/tailwind.output.css HTTP/1.1" 500 145
Internal Server Error: /static/img/body.webp
"GET /static/img/body.webp HTTP/1.1" 500 145
Internal Server Error: /static/css/tailwind.output.css
"GET /static/css/tailwind.output.css HTTP/1.1" 500 145
Internal Server Error: /static/img/body.webp
"GET /static/img/body.webp HTTP/1.1" 500 145
Internal Server Error: /static/css/tailwind.output.css
"GET /static/css/tailwind.output.css HTTP/1.1" 500 145
Internal Server Error: /static/css/tailwind.output.css
"GET /static/css/tailwind.output.css HTTP/1.1" 500 145
Internal Server Error: /static/img/body.webp
"GET /static/img/body.webp HTTP/1.1" 500 145
Internal Server Error: /static/css/tailwind.output.css
"GET /static/css/tailwind.output.css HTTP/1.1" 500 145
Internal Server Error: /static/img/body.webp
"GET /static/img/body.webp HTTP/1.1" 500 145
Internal Server Error: /favicon.ico
"GET /favicon.ico HTTP/1.1" 500 145
Internal Server Error: /static/css/tailwind.output.css
"GET /static/css/tailwind.output.css HTTP/1.1" 500 145
Internal Server Error: /static/css/tailwind.output.css
"GET /static/css/tailwind.output.css HTTP/1.1" 500 145
Internal Server Error: /static/img/body.webp
"GET /static/img/body.webp HTTP/1.1" 500 145
Internal Server Error: /favicon.ico
"GET /favicon.ico HTTP/1.1" 500 145
Internal Server Error: /feeds/detail/2/
Traceback (most recent call last):
  File "C:\Users\p-gar\PycharmProjects\ResearchTracker\.venv\Lib\site-packages\django\template\defaulttags.py", line 1034, in find_library
    return parser.libraries[name]
           ~~~~~~~~~~~~~~~~^^^^^^
KeyError: 'custom_filters'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\p-gar\PycharmProjects\ResearchTracker\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\p-gar\PycharmProjects\ResearchTracker\.venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\p-gar\PycharmProjects\ResearchTracker\.venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\p-gar\PycharmProjects\ResearchTracker\.venv\Lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\p-gar\PycharmProjects\ResearchTracker\.venv\Lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\p-gar\PycharmProjects\ResearchTracker\.venv\Lib\site-packages\django\template\loader.py", line 42, in select_template
    return engine.get_template(template_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\p-gar\PycharmProjects\ResearchTracker\.venv\Lib\site-packages\django\template\backends\django.py", line 33, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\p-gar\PycharmProjects\ResearchTracker\.venv\Lib\site-packages\django\template\engine.py", line 177, in get_template
    template, origin = self.find_template(template_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\p-gar\PycharmProjects\ResearchTracker\.venv\Lib\site-packages\django\template\engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\p-gar\PycharmProjects\ResearchTracker\.venv\Lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\p-gar\PycharmProjects\ResearchTracker\.venv\Lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
           ^^^^^^^^^
  File "C:\Users\p-gar\PycharmProjects\ResearchTracker\.venv\Lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\p-gar\PycharmProjects\ResearchTracker\.venv\Lib\site-packages\django\template\base.py", line 196, in compile_nodelist
    return parser.parse()
           ^^^^^^^^^^^^^^
  File "C:\Users\p-gar\PycharmProjects\ResearchTracker\.venv\Lib\site-packages\django\template\base.py", line 510, in parse
    raise self.error(token, e)
  File "C:\Users\p-gar\PycharmProjects\ResearchTracker\.venv\Lib\site-packages\django\template\base.py", line 508, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\p-gar\PycharmProjects\ResearchTracker\.venv\Lib\site-packages\django\template\loader_tags.py", line 295, in do_extends
    nodelist = parser.parse()
               ^^^^^^^^^^^^^^
  File "C:\Users\p-gar\PycharmProjects\ResearchTracker\.venv\Lib\site-packages\django\template\base.py", line 510, in parse
    raise self.error(token, e)
  File "C:\Users\p-gar\PycharmProjects\ResearchTracker\.venv\Lib\site-packages\django\template\base.py", line 508, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\p-gar\PycharmProjects\ResearchTracker\.venv\Lib\site-packages\django\template\defaulttags.py", line 1096, in load
    lib = find_library(parser, name)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\p-gar\PycharmProjects\ResearchTracker\.venv\Lib\site-packages\django\template\defaulttags.py", line 1036, in find_library
    raise TemplateSyntaxError(
django.template.exceptions.TemplateSyntaxError: 'custom_filters' is not a registered tag library. Must be one of:
admin_list
admin_modify
admin_urls
cache
i18n
l10n
log
rest_framework
static
tz
"GET /feeds/detail/2/ HTTP/1.1" 500 177603
Internal Server Error: /feeds/detail/2/
Traceback (most recent call last):
  File "C:\Users\p-gar\PycharmProjects\ResearchTracker\feeds\templatetags\custom_filters.py", line 19, in format_datetime
    dt = datetime.strptime(value, '%a, %d %b %Y %H:%M:%S %z')
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\_strptime.py", line 554, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\_strptime.py", line 333, in _strptime
    raise ValueError("time data %r does not match format %r" %
ValueError: time data 'Mon, 03 Jun 2024 08:30:08 +0200' does not match format '%a, %d %b %Y %H:%M:%S %z'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\p-gar\PycharmProjects\ResearchTracker\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\p-gar\PycharmProjects\ResearchTracker\.venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\p-gar\PycharmProjects\ResearchTracker\.venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\p-gar\PycharmProjects\ResearchTracker\.venv\Lib\site-packages\django\template\response.py", line 92, in rendered_content
    return template.render(context, self._request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\p-gar\PycharmProjects\ResearchTracker\.venv\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\p-gar\PycharmProjects\ResearchTracker\.venv\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\p-gar\PycharmProjects\ResearchTracker\.venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\p-gar\PycharmProjects\ResearchTracker\.venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\p-gar\PycharmProjects\ResearchTracker\.venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\p-gar\PycharmProjects\ResearchTracker\.venv\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\p-gar\PycharmProjects\ResearchTracker\.venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\p-gar\PycharmProjects\ResearchTracker\.venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\p-gar\PycharmProjects\ResearchTracker\.venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\p-gar\PycharmProjects\ResearchTracker\.venv\Lib\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\p-gar\PycharmProjects\ResearchTracker\.venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\p-gar\PycharmProjects\ResearchTracker\.venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\p-gar\PycharmProjects\ResearchTracker\.venv\Lib\site-packages\django\template\defaulttags.py", line 242, in render
    nodelist.append(node.render_annotated(context))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\p-gar\PycharmProjects\ResearchTracker\.venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\p-gar\PycharmProjects\ResearchTracker\.venv\Lib\site-packages\django\template\base.py", line 1059, in render
    output = self.filter_expression.resolve(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\p-gar\PycharmProjects\ResearchTracker\.venv\Lib\site-packages\django\template\base.py", line 737, in resolve
    new_obj = func(obj, *arg_vals)
              ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\p-gar\PycharmProjects\ResearchTracker\feeds\templatetags\custom_filters.py", line 22, in format_datetime
    dt = datetime.strptime(value, '%Y-%m-%dT%H:%M:%S%z')
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\_strptime.py", line 554, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\_strptime.py", line 333, in _strptime
    raise ValueError("time data %r does not match format %r" %
ValueError: time data 'Mon, 03 Jun 2024 08:30:08 +0200' does not match format '%Y-%m-%dT%H:%M:%S%z'
"GET /feeds/detail/2/ HTTP/1.1" 500 283296
Internal Server Error: /feeds/detail/2/
Traceback (most recent call last):
  File "C:\Users\p-gar\PycharmProjects\ResearchTracker\feeds\templatetags\custom_filters.py", line 19, in format_datetime
    dt = datetime.strptime(value, '%a, %d %b %Y %H:%M:%S %z')
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\_strptime.py", line 554, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\_strptime.py", line 333, in _strptime
    raise ValueError("time data %r does not match format %r" %
ValueError: time data 'Mon, 03 Jun 2024 08:30:08 +0200' does not match format '%a, %d %b %Y %H:%M:%S %z'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\p-gar\PycharmProjects\ResearchTracker\feeds\templatetags\custom_filters.py", line 23, in format_datetime
    dt = datetime.strptime(value, '%Y-%m-%dT%H:%M:%S%z')
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\_strptime.py", line 554, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\_strptime.py", line 333, in _strptime
    raise ValueError("time data %r does not match format %r" %
ValueError: time data 'Mon, 03 Jun 2024 08:30:08 +0200' does not match format '%Y-%m-%dT%H:%M:%S%z'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\p-gar\PycharmProjects\ResearchTracker\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\p-gar\PycharmProjects\ResearchTracker\.venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\p-gar\PycharmProjects\ResearchTracker\.venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\p-gar\PycharmProjects\ResearchTracker\.venv\Lib\site-packages\django\template\response.py", line 92, in rendered_content
    return template.render(context, self._request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\p-gar\PycharmProjects\ResearchTracker\.venv\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\p-gar\PycharmProjects\ResearchTracker\.venv\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\p-gar\PycharmProjects\ResearchTracker\.venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\p-gar\PycharmProjects\ResearchTracker\.venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\p-gar\PycharmProjects\ResearchTracker\.venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\p-gar\PycharmProjects\ResearchTracker\.venv\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\p-gar\PycharmProjects\ResearchTracker\.venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\p-gar\PycharmProjects\ResearchTracker\.venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\p-gar\PycharmProjects\ResearchTracker\.venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\p-gar\PycharmProjects\ResearchTracker\.venv\Lib\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\p-gar\PycharmProjects\ResearchTracker\.venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\p-gar\PycharmProjects\ResearchTracker\.venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\p-gar\PycharmProjects\ResearchTracker\.venv\Lib\site-packages\django\template\defaulttags.py", line 242, in render
    nodelist.append(node.render_annotated(context))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\p-gar\PycharmProjects\ResearchTracker\.venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\p-gar\PycharmProjects\ResearchTracker\.venv\Lib\site-packages\django\template\base.py", line 1059, in render
    output = self.filter_expression.resolve(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\p-gar\PycharmProjects\ResearchTracker\.venv\Lib\site-packages\django\template\base.py", line 737, in resolve
    new_obj = func(obj, *arg_vals)
              ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\p-gar\PycharmProjects\ResearchTracker\feeds\templatetags\custom_filters.py", line 25, in format_datetime
    dt = datetime.strptime(value, '%a, %d %b %Y %H:%M:%S %z')
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\_strptime.py", line 554, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\_strptime.py", line 333, in _strptime
    raise ValueError("time data %r does not match format %r" %
ValueError: time data 'Mon, 03 Jun 2024 08:30:08 +0200' does not match format '%a, %d %b %Y %H:%M:%S %z'
"GET /feeds/detail/2/ HTTP/1.1" 500 296911
Internal Server Error: /feeds/detail/2/
Traceback (most recent call last):
  File "C:\Users\p-gar\PycharmProjects\ResearchTracker\feeds\templatetags\custom_filters.py", line 19, in format_datetime
    dt = datetime.strptime(value, '%a, %d %b %Y %H:%M:%S %z')
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\_strptime.py", line 554, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\_strptime.py", line 333, in _strptime
    raise ValueError("time data %r does not match format %r" %
ValueError: time data 'Mon, 03 Jun 2024 08:30:08 +0200' does not match format '%a, %d %b %Y %H:%M:%S %z'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\p-gar\PycharmProjects\ResearchTracker\feeds\templatetags\custom_filters.py", line 23, in format_datetime
    dt = datetime.strptime(value, '%Y-%m-%dT%H:%M:%S%z')
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\_strptime.py", line 554, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\_strptime.py", line 333, in _strptime
    raise ValueError("time data %r does not match format %r" %
ValueError: time data 'Mon, 03 Jun 2024 08:30:08 +0200' does not match format '%Y-%m-%dT%H:%M:%S%z'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\p-gar\PycharmProjects\ResearchTracker\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\p-gar\PycharmProjects\ResearchTracker\.venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\p-gar\PycharmProjects\ResearchTracker\.venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\p-gar\PycharmProjects\ResearchTracker\.venv\Lib\site-packages\django\template\response.py", line 92, in rendered_content
    return template.render(context, self._request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\p-gar\PycharmProjects\ResearchTracker\.venv\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\p-gar\PycharmProjects\ResearchTracker\.venv\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\p-gar\PycharmProjects\ResearchTracker\.venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\p-gar\PycharmProjects\ResearchTracker\.venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\p-gar\PycharmProjects\ResearchTracker\.venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\p-gar\PycharmProjects\ResearchTracker\.venv\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\p-gar\PycharmProjects\ResearchTracker\.venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\p-gar\PycharmProjects\ResearchTracker\.venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\p-gar\PycharmProjects\ResearchTracker\.venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\p-gar\PycharmProjects\ResearchTracker\.venv\Lib\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\p-gar\PycharmProjects\ResearchTracker\.venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\p-gar\PycharmProjects\ResearchTracker\.venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\p-gar\PycharmProjects\ResearchTracker\.venv\Lib\site-packages\django\template\defaulttags.py", line 242, in render
    nodelist.append(node.render_annotated(context))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\p-gar\PycharmProjects\ResearchTracker\.venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\p-gar\PycharmProjects\ResearchTracker\.venv\Lib\site-packages\django\template\base.py", line 1059, in render
    output = self.filter_expression.resolve(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\p-gar\PycharmProjects\ResearchTracker\.venv\Lib\site-packages\django\template\base.py", line 737, in resolve
    new_obj = func(obj, *arg_vals)
              ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\p-gar\PycharmProjects\ResearchTracker\feeds\templatetags\custom_filters.py", line 25, in format_datetime
    dt = datetime.strptime(value, '%a, %d %b %Y %H:%M:%S %z')
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\_strptime.py", line 554, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\_strptime.py", line 333, in _strptime
    raise ValueError("time data %r does not match format %r" %
ValueError: time data 'Mon, 03 Jun 2024 08:30:08 +0200' does not match format '%a, %d %b %Y %H:%M:%S %z'
"GET /feeds/detail/2/ HTTP/1.1" 500 296911
Internal Server Error: /feeds/detail/2/
Traceback (most recent call last):
  File "C:\Users\p-gar\PycharmProjects\ResearchTracker\feeds\templatetags\custom_filters.py", line 19, in format_datetime
    dt = datetime.strptime(value, '%a, %d %b %Y %H:%M:%S %z')
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\_strptime.py", line 554, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\_strptime.py", line 333, in _strptime
    raise ValueError("time data %r does not match format %r" %
ValueError: time data 'Mon, 03 Jun 2024 08:30:08 +0200' does not match format '%a, %d %b %Y %H:%M:%S %z'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\p-gar\PycharmProjects\ResearchTracker\feeds\templatetags\custom_filters.py", line 23, in format_datetime
    dt = datetime.strptime(value, '%Y-%m-%dT%H:%M:%S%z')
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\_strptime.py", line 554, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\_strptime.py", line 333, in _strptime
    raise ValueError("time data %r does not match format %r" %
ValueError: time data 'Mon, 03 Jun 2024 08:30:08 +0200' does not match format '%Y-%m-%dT%H:%M:%S%z'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\p-gar\PycharmProjects\ResearchTracker\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\p-gar\PycharmProjects\ResearchTracker\.venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\p-gar\PycharmProjects\ResearchTracker\.venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\p-gar\PycharmProjects\ResearchTracker\.venv\Lib\site-packages\django\template\response.py", line 92, in rendered_content
    return template.render(context, self._request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\p-gar\PycharmProjects\ResearchTracker\.venv\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\p-gar\PycharmProjects\ResearchTracker\.venv\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\p-gar\PycharmProjects\ResearchTracker\.venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\p-gar\PycharmProjects\ResearchTracker\.venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\p-gar\PycharmProjects\ResearchTracker\.venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\p-gar\PycharmProjects\ResearchTracker\.venv\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\p-gar\PycharmProjects\ResearchTracker\.venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\p-gar\PycharmProjects\ResearchTracker\.venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\p-gar\PycharmProjects\ResearchTracker\.venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\p-gar\PycharmProjects\ResearchTracker\.venv\Lib\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\p-gar\PycharmProjects\ResearchTracker\.venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\p-gar\PycharmProjects\ResearchTracker\.venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\p-gar\PycharmProjects\ResearchTracker\.venv\Lib\site-packages\django\template\defaulttags.py", line 242, in render
    nodelist.append(node.render_annotated(context))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\p-gar\PycharmProjects\ResearchTracker\.venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\p-gar\PycharmProjects\ResearchTracker\.venv\Lib\site-packages\django\template\base.py", line 1059, in render
    output = self.filter_expression.resolve(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\p-gar\PycharmProjects\ResearchTracker\.venv\Lib\site-packages\django\template\base.py", line 737, in resolve
    new_obj = func(obj, *arg_vals)
              ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\p-gar\PycharmProjects\ResearchTracker\feeds\templatetags\custom_filters.py", line 25, in format_datetime
    dt = datetime.strptime(value, '%a, %d %b %Y %H:%M:%S %z')
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\_strptime.py", line 554, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\_strptime.py", line 333, in _strptime
    raise ValueError("time data %r does not match format %r" %
ValueError: time data 'Mon, 03 Jun 2024 08:30:08 +0200' does not match format '%a, %d %b %Y %H:%M:%S %z'
"GET /feeds/detail/2/ HTTP/1.1" 500 296911
Internal Server Error: /feeds/detail/2/
Traceback (most recent call last):
  File "C:\Users\p-gar\PycharmProjects\ResearchTracker\feeds\templatetags\custom_filters.py", line 19, in format_datetime
    dt = datetime.strptime(value, '%a, %d %b %Y %H:%M:%S %z')
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\_strptime.py", line 554, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\_strptime.py", line 333, in _strptime
    raise ValueError("time data %r does not match format %r" %
ValueError: time data 'Mon, 03 Jun 2024 08:30:08 +0200' does not match format '%a, %d %b %Y %H:%M:%S %z'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\p-gar\PycharmProjects\ResearchTracker\feeds\templatetags\custom_filters.py", line 23, in format_datetime
    dt = datetime.strptime(value, '%Y-%m-%dT%H:%M:%S%z')
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\_strptime.py", line 554, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\_strptime.py", line 333, in _strptime
    raise ValueError("time data %r does not match format %r" %
ValueError: time data 'Mon, 03 Jun 2024 08:30:08 +0200' does not match format '%Y-%m-%dT%H:%M:%S%z'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\p-gar\PycharmProjects\ResearchTracker\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\p-gar\PycharmProjects\ResearchTracker\.venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\p-gar\PycharmProjects\ResearchTracker\.venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\p-gar\PycharmProjects\ResearchTracker\.venv\Lib\site-packages\django\template\response.py", line 92, in rendered_content
    return template.render(context, self._request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\p-gar\PycharmProjects\ResearchTracker\.venv\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\p-gar\PycharmProjects\ResearchTracker\.venv\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\p-gar\PycharmProjects\ResearchTracker\.venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\p-gar\PycharmProjects\ResearchTracker\.venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\p-gar\PycharmProjects\ResearchTracker\.venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\p-gar\PycharmProjects\ResearchTracker\.venv\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\p-gar\PycharmProjects\ResearchTracker\.venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\p-gar\PycharmProjects\ResearchTracker\.venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\p-gar\PycharmProjects\ResearchTracker\.venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\p-gar\PycharmProjects\ResearchTracker\.venv\Lib\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\p-gar\PycharmProjects\ResearchTracker\.venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\p-gar\PycharmProjects\ResearchTracker\.venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\p-gar\PycharmProjects\ResearchTracker\.venv\Lib\site-packages\django\template\defaulttags.py", line 242, in render
    nodelist.append(node.render_annotated(context))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\p-gar\PycharmProjects\ResearchTracker\.venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\p-gar\PycharmProjects\ResearchTracker\.venv\Lib\site-packages\django\template\base.py", line 1059, in render
    output = self.filter_expression.resolve(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\p-gar\PycharmProjects\ResearchTracker\.venv\Lib\site-packages\django\template\base.py", line 737, in resolve
    new_obj = func(obj, *arg_vals)
              ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\p-gar\PycharmProjects\ResearchTracker\feeds\templatetags\custom_filters.py", line 25, in format_datetime
    dt = datetime.strptime(value, '%a, %d %b %Y %H:%M:%S %z')
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\_strptime.py", line 554, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\_strptime.py", line 333, in _strptime
    raise ValueError("time data %r does not match format %r" %
ValueError: time data 'Mon, 03 Jun 2024 08:30:08 +0200' does not match format '%a, %d %b %Y %H:%M:%S %z'
"GET /feeds/detail/2/ HTTP/1.1" 500 296911
Internal Server Error: /feeds/detail/2/
Traceback (most recent call last):
  File "C:\Users\p-gar\PycharmProjects\ResearchTracker\feeds\templatetags\custom_filters.py", line 19, in format_datetime
    dt = datetime.strptime(value, '%a, %d %b %Y %H:%M:%S %z')
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\_strptime.py", line 554, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\_strptime.py", line 333, in _strptime
    raise ValueError("time data %r does not match format %r" %
ValueError: time data 'Sun, 02 Jun 2024 22:00:02 +0200' does not match format '%a, %d %b %Y %H:%M:%S %z'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\p-gar\PycharmProjects\ResearchTracker\feeds\templatetags\custom_filters.py", line 23, in format_datetime
    dt = datetime.strptime(value, '%Y-%m-%dT%H:%M:%S%z')
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\_strptime.py", line 554, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\_strptime.py", line 333, in _strptime
    raise ValueError("time data %r does not match format %r" %
ValueError: time data 'Sun, 02 Jun 2024 22:00:02 +0200' does not match format '%Y-%m-%dT%H:%M:%S%z'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\p-gar\PycharmProjects\ResearchTracker\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\p-gar\PycharmProjects\ResearchTracker\.venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\p-gar\PycharmProjects\ResearchTracker\.venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\p-gar\PycharmProjects\ResearchTracker\.venv\Lib\site-packages\django\template\response.py", line 92, in rendered_content
    return template.render(context, self._request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\p-gar\PycharmProjects\ResearchTracker\.venv\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\p-gar\PycharmProjects\ResearchTracker\.venv\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\p-gar\PycharmProjects\ResearchTracker\.venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\p-gar\PycharmProjects\ResearchTracker\.venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\p-gar\PycharmProjects\ResearchTracker\.venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\p-gar\PycharmProjects\ResearchTracker\.venv\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\p-gar\PycharmProjects\ResearchTracker\.venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\p-gar\PycharmProjects\ResearchTracker\.venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\p-gar\PycharmProjects\ResearchTracker\.venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\p-gar\PycharmProjects\ResearchTracker\.venv\Lib\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\p-gar\PycharmProjects\ResearchTracker\.venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\p-gar\PycharmProjects\ResearchTracker\.venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\p-gar\PycharmProjects\ResearchTracker\.venv\Lib\site-packages\django\template\defaulttags.py", line 242, in render
    nodelist.append(node.render_annotated(context))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\p-gar\PycharmProjects\ResearchTracker\.venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\p-gar\PycharmProjects\ResearchTracker\.venv\Lib\site-packages\django\template\base.py", line 1059, in render
    output = self.filter_expression.resolve(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\p-gar\PycharmProjects\ResearchTracker\.venv\Lib\site-packages\django\template\base.py", line 737, in resolve
    new_obj = func(obj, *arg_vals)
              ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\p-gar\PycharmProjects\ResearchTracker\feeds\templatetags\custom_filters.py", line 25, in format_datetime
    dt = datetime.strptime(value, '%a, %d %b %Y %H:%M:%S %z')
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\_strptime.py", line 554, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\_strptime.py", line 333, in _strptime
    raise ValueError("time data %r does not match format %r" %
ValueError: time data 'Sun, 02 Jun 2024 22:00:02 +0200' does not match format '%a, %d %b %Y %H:%M:%S %z'
"GET /feeds/detail/2/ HTTP/1.1" 500 299528
Internal Server Error: /feeds/detail/1/
Traceback (most recent call last):
  File "C:\Users\p-gar\PycharmProjects\ResearchTracker\feeds\templatetags\custom_filters.py", line 19, in format_datetime
    dt = datetime.strptime(value, '%a, %d %b %Y %H:%M:%S %z')
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\_strptime.py", line 554, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\_strptime.py", line 333, in _strptime
    raise ValueError("time data %r does not match format %r" %
ValueError: time data 'Thu, 30 May 2024 09:00:27 +0000' does not match format '%a, %d %b %Y %H:%M:%S %z'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\p-gar\PycharmProjects\ResearchTracker\feeds\templatetags\custom_filters.py", line 23, in format_datetime
    dt = datetime.strptime(value, '%Y-%m-%dT%H:%M:%S%z')
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\_strptime.py", line 554, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\_strptime.py", line 333, in _strptime
    raise ValueError("time data %r does not match format %r" %
ValueError: time data 'Thu, 30 May 2024 09:00:27 +0000' does not match format '%Y-%m-%dT%H:%M:%S%z'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\p-gar\PycharmProjects\ResearchTracker\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\p-gar\PycharmProjects\ResearchTracker\.venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\p-gar\PycharmProjects\ResearchTracker\.venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\p-gar\PycharmProjects\ResearchTracker\.venv\Lib\site-packages\django\template\response.py", line 92, in rendered_content
    return template.render(context, self._request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\p-gar\PycharmProjects\ResearchTracker\.venv\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\p-gar\PycharmProjects\ResearchTracker\.venv\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\p-gar\PycharmProjects\ResearchTracker\.venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\p-gar\PycharmProjects\ResearchTracker\.venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\p-gar\PycharmProjects\ResearchTracker\.venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\p-gar\PycharmProjects\ResearchTracker\.venv\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\p-gar\PycharmProjects\ResearchTracker\.venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\p-gar\PycharmProjects\ResearchTracker\.venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\p-gar\PycharmProjects\ResearchTracker\.venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\p-gar\PycharmProjects\ResearchTracker\.venv\Lib\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\p-gar\PycharmProjects\ResearchTracker\.venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\p-gar\PycharmProjects\ResearchTracker\.venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\p-gar\PycharmProjects\ResearchTracker\.venv\Lib\site-packages\django\template\defaulttags.py", line 242, in render
    nodelist.append(node.render_annotated(context))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\p-gar\PycharmProjects\ResearchTracker\.venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\p-gar\PycharmProjects\ResearchTracker\.venv\Lib\site-packages\django\template\base.py", line 1059, in render
    output = self.filter_expression.resolve(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\p-gar\PycharmProjects\ResearchTracker\.venv\Lib\site-packages\django\template\base.py", line 737, in resolve
    new_obj = func(obj, *arg_vals)
              ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\p-gar\PycharmProjects\ResearchTracker\feeds\templatetags\custom_filters.py", line 25, in format_datetime
    dt = datetime.strptime(value, '%a, %d %b %Y %H:%M:%S %z')
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\_strptime.py", line 554, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\_strptime.py", line 333, in _strptime
    raise ValueError("time data %r does not match format %r" %
ValueError: time data 'Thu, 30 May 2024 09:00:27 +0000' does not match format '%a, %d %b %Y %H:%M:%S %z'
"GET /feeds/detail/1/ HTTP/1.1" 500 299818
Internal Server Error: /feeds/detail/1/
Traceback (most recent call last):
  File "C:\Users\p-gar\PycharmProjects\ResearchTracker\feeds\templatetags\custom_filters.py", line 20, in format_datetime
    dt = datetime.strptime(value, '%a, %d %b %Y %H:%M:%S %z')
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\_strptime.py", line 554, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\_strptime.py", line 333, in _strptime
    raise ValueError("time data %r does not match format %r" %
ValueError: time data 'Thu, 30 May 2024 08:15:02 +0000' does not match format '%a, %d %b %Y %H:%M:%S %z'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\p-gar\PycharmProjects\ResearchTracker\feeds\templatetags\custom_filters.py", line 24, in format_datetime
    dt = datetime.strptime(value, '%Y-%m-%dT%H:%M:%S%z')
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\_strptime.py", line 554, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\_strptime.py", line 333, in _strptime
    raise ValueError("time data %r does not match format %r" %
ValueError: time data 'Thu, 30 May 2024 08:15:02 +0000' does not match format '%Y-%m-%dT%H:%M:%S%z'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\p-gar\PycharmProjects\ResearchTracker\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\p-gar\PycharmProjects\ResearchTracker\.venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\p-gar\PycharmProjects\ResearchTracker\.venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\p-gar\PycharmProjects\ResearchTracker\.venv\Lib\site-packages\django\template\response.py", line 92, in rendered_content
    return template.render(context, self._request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\p-gar\PycharmProjects\ResearchTracker\.venv\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\p-gar\PycharmProjects\ResearchTracker\.venv\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\p-gar\PycharmProjects\ResearchTracker\.venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\p-gar\PycharmProjects\ResearchTracker\.venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\p-gar\PycharmProjects\ResearchTracker\.venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\p-gar\PycharmProjects\ResearchTracker\.venv\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\p-gar\PycharmProjects\ResearchTracker\.venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\p-gar\PycharmProjects\ResearchTracker\.venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\p-gar\PycharmProjects\ResearchTracker\.venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\p-gar\PycharmProjects\ResearchTracker\.venv\Lib\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\p-gar\PycharmProjects\ResearchTracker\.venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\p-gar\PycharmProjects\ResearchTracker\.venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\p-gar\PycharmProjects\ResearchTracker\.venv\Lib\site-packages\django\template\defaulttags.py", line 242, in render
    nodelist.append(node.render_annotated(context))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\p-gar\PycharmProjects\ResearchTracker\.venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\p-gar\PycharmProjects\ResearchTracker\.venv\Lib\site-packages\django\template\base.py", line 1059, in render
    output = self.filter_expression.resolve(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\p-gar\PycharmProjects\ResearchTracker\.venv\Lib\site-packages\django\template\base.py", line 737, in resolve
    new_obj = func(obj, *arg_vals)
              ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\p-gar\PycharmProjects\ResearchTracker\feeds\templatetags\custom_filters.py", line 26, in format_datetime
    dt = datetime.strptime(value, '%a, %d %b %Y %H:%M:%S %z')
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\_strptime.py", line 554, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\_strptime.py", line 333, in _strptime
    raise ValueError("time data %r does not match format %r" %
ValueError: time data 'Thu, 30 May 2024 08:15:02 +0000' does not match format '%a, %d %b %Y %H:%M:%S %z'
"GET /feeds/detail/1/ HTTP/1.1" 500 301612
Internal Server Error: /feeds/detail/2/
Traceback (most recent call last):
  File "C:\Users\p-gar\PycharmProjects\ResearchTracker\feeds\templatetags\custom_filters.py", line 20, in format_datetime
    dt = datetime.strptime(value, '%a, %d %b %Y %H:%M:%S %z')
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\_strptime.py", line 554, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\_strptime.py", line 333, in _strptime
    raise ValueError("time data %r does not match format %r" %
ValueError: time data 'Mon, 03 Jun 2024 08:30:08 +0200' does not match format '%a, %d %b %Y %H:%M:%S %z'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\p-gar\PycharmProjects\ResearchTracker\feeds\templatetags\custom_filters.py", line 24, in format_datetime
    dt = datetime.strptime(value, '%Y-%m-%dT%H:%M:%S%z')
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\_strptime.py", line 554, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\_strptime.py", line 333, in _strptime
    raise ValueError("time data %r does not match format %r" %
ValueError: time data 'Mon, 03 Jun 2024 08:30:08 +0200' does not match format '%Y-%m-%dT%H:%M:%S%z'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\p-gar\PycharmProjects\ResearchTracker\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\p-gar\PycharmProjects\ResearchTracker\.venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\p-gar\PycharmProjects\ResearchTracker\.venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\p-gar\PycharmProjects\ResearchTracker\.venv\Lib\site-packages\django\template\response.py", line 92, in rendered_content
    return template.render(context, self._request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\p-gar\PycharmProjects\ResearchTracker\.venv\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\p-gar\PycharmProjects\ResearchTracker\.venv\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\p-gar\PycharmProjects\ResearchTracker\.venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\p-gar\PycharmProjects\ResearchTracker\.venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\p-gar\PycharmProjects\ResearchTracker\.venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\p-gar\PycharmProjects\ResearchTracker\.venv\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\p-gar\PycharmProjects\ResearchTracker\.venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\p-gar\PycharmProjects\ResearchTracker\.venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\p-gar\PycharmProjects\ResearchTracker\.venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\p-gar\PycharmProjects\ResearchTracker\.venv\Lib\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\p-gar\PycharmProjects\ResearchTracker\.venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\p-gar\PycharmProjects\ResearchTracker\.venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\p-gar\PycharmProjects\ResearchTracker\.venv\Lib\site-packages\django\template\defaulttags.py", line 242, in render
    nodelist.append(node.render_annotated(context))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\p-gar\PycharmProjects\ResearchTracker\.venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\p-gar\PycharmProjects\ResearchTracker\.venv\Lib\site-packages\django\template\base.py", line 1059, in render
    output = self.filter_expression.resolve(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\p-gar\PycharmProjects\ResearchTracker\.venv\Lib\site-packages\django\template\base.py", line 737, in resolve
    new_obj = func(obj, *arg_vals)
              ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\p-gar\PycharmProjects\ResearchTracker\feeds\templatetags\custom_filters.py", line 26, in format_datetime
    dt = datetime.strptime(value, '%a, %d %b %Y %H:%M:%S %z')
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\_strptime.py", line 554, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\_strptime.py", line 333, in _strptime
    raise ValueError("time data %r does not match format %r" %
ValueError: time data 'Mon, 03 Jun 2024 08:30:08 +0200' does not match format '%a, %d %b %Y %H:%M:%S %z'
"GET /feeds/detail/2/ HTTP/1.1" 500 297417
Internal Server Error: /feeds/detail/1/
Traceback (most recent call last):
  File "C:\Users\p-gar\PycharmProjects\ResearchTracker\feeds\templatetags\custom_filters.py", line 20, in format_datetime
    dt = datetime.strptime(value, '%a, %d %b %Y %H:%M:%S %z')
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\_strptime.py", line 554, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\_strptime.py", line 333, in _strptime
    raise ValueError("time data %r does not match format %r" %
ValueError: time data 'Thu, 30 May 2024 08:15:02 +0000' does not match format '%a, %d %b %Y %H:%M:%S %z'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\p-gar\PycharmProjects\ResearchTracker\feeds\templatetags\custom_filters.py", line 24, in format_datetime
    dt = datetime.strptime(value, '%Y-%m-%dT%H:%M:%S%z')
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\_strptime.py", line 554, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\_strptime.py", line 333, in _strptime
    raise ValueError("time data %r does not match format %r" %
ValueError: time data 'Thu, 30 May 2024 08:15:02 +0000' does not match format '%Y-%m-%dT%H:%M:%S%z'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\p-gar\PycharmProjects\ResearchTracker\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\p-gar\PycharmProjects\ResearchTracker\.venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\p-gar\PycharmProjects\ResearchTracker\.venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\p-gar\PycharmProjects\ResearchTracker\.venv\Lib\site-packages\django\template\response.py", line 92, in rendered_content
    return template.render(context, self._request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\p-gar\PycharmProjects\ResearchTracker\.venv\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\p-gar\PycharmProjects\ResearchTracker\.venv\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\p-gar\PycharmProjects\ResearchTracker\.venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\p-gar\PycharmProjects\ResearchTracker\.venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\p-gar\PycharmProjects\ResearchTracker\.venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\p-gar\PycharmProjects\ResearchTracker\.venv\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\p-gar\PycharmProjects\ResearchTracker\.venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\p-gar\PycharmProjects\ResearchTracker\.venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\p-gar\PycharmProjects\ResearchTracker\.venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\p-gar\PycharmProjects\ResearchTracker\.venv\Lib\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\p-gar\PycharmProjects\ResearchTracker\.venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\p-gar\PycharmProjects\ResearchTracker\.venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\p-gar\PycharmProjects\ResearchTracker\.venv\Lib\site-packages\django\template\defaulttags.py", line 242, in render
    nodelist.append(node.render_annotated(context))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\p-gar\PycharmProjects\ResearchTracker\.venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\p-gar\PycharmProjects\ResearchTracker\.venv\Lib\site-packages\django\template\base.py", line 1059, in render
    output = self.filter_expression.resolve(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\p-gar\PycharmProjects\ResearchTracker\.venv\Lib\site-packages\django\template\base.py", line 737, in resolve
    new_obj = func(obj, *arg_vals)
              ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\p-gar\PycharmProjects\ResearchTracker\feeds\templatetags\custom_filters.py", line 26, in format_datetime
    dt = datetime.strptime(value, '%a, %d %b %Y %H:%M:%S %z')
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\_strptime.py", line 554, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\_strptime.py", line 333, in _strptime
    raise ValueError("time data %r does not match format %r" %
ValueError: time data 'Thu, 30 May 2024 08:15:02 +0000' does not match format '%a, %d %b %Y %H:%M:%S %z'
"GET /feeds/detail/1/ HTTP/1.1" 500 301340
Internal Server Error: /feeds/detail/1/
Traceback (most recent call last):
  File "C:\Users\p-gar\PycharmProjects\ResearchTracker\feeds\templatetags\custom_filters.py", line 20, in format_datetime
    dt = datetime.strptime(value, '%a, %d %b %Y %H:%M:%S %z')
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\_strptime.py", line 554, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\_strptime.py", line 333, in _strptime
    raise ValueError("time data %r does not match format %r" %
ValueError: time data 'Thu, 30 May 2024 09:00:27 +0000' does not match format '%a, %d %b %Y %H:%M:%S %z'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\p-gar\PycharmProjects\ResearchTracker\feeds\templatetags\custom_filters.py", line 24, in format_datetime
    dt = datetime.strptime(value, '%Y-%m-%dT%H:%M:%S%z')
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\_strptime.py", line 554, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\_strptime.py", line 333, in _strptime
    raise ValueError("time data %r does not match format %r" %
ValueError: time data 'Thu, 30 May 2024 09:00:27 +0000' does not match format '%Y-%m-%dT%H:%M:%S%z'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\p-gar\PycharmProjects\ResearchTracker\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\p-gar\PycharmProjects\ResearchTracker\.venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\p-gar\PycharmProjects\ResearchTracker\.venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\p-gar\PycharmProjects\ResearchTracker\.venv\Lib\site-packages\django\template\response.py", line 92, in rendered_content
    return template.render(context, self._request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\p-gar\PycharmProjects\ResearchTracker\.venv\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\p-gar\PycharmProjects\ResearchTracker\.venv\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\p-gar\PycharmProjects\ResearchTracker\.venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\p-gar\PycharmProjects\ResearchTracker\.venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\p-gar\PycharmProjects\ResearchTracker\.venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\p-gar\PycharmProjects\ResearchTracker\.venv\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\p-gar\PycharmProjects\ResearchTracker\.venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\p-gar\PycharmProjects\ResearchTracker\.venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\p-gar\PycharmProjects\ResearchTracker\.venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\p-gar\PycharmProjects\ResearchTracker\.venv\Lib\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\p-gar\PycharmProjects\ResearchTracker\.venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\p-gar\PycharmProjects\ResearchTracker\.venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\p-gar\PycharmProjects\ResearchTracker\.venv\Lib\site-packages\django\template\defaulttags.py", line 242, in render
    nodelist.append(node.render_annotated(context))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\p-gar\PycharmProjects\ResearchTracker\.venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\p-gar\PycharmProjects\ResearchTracker\.venv\Lib\site-packages\django\template\base.py", line 1059, in render
    output = self.filter_expression.resolve(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\p-gar\PycharmProjects\ResearchTracker\.venv\Lib\site-packages\django\template\base.py", line 737, in resolve
    new_obj = func(obj, *arg_vals)
              ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\p-gar\PycharmProjects\ResearchTracker\feeds\templatetags\custom_filters.py", line 26, in format_datetime
    dt = datetime.strptime(value, '%a, %d %b %Y %H:%M:%S %z')
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\_strptime.py", line 554, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\_strptime.py", line 333, in _strptime
    raise ValueError("time data %r does not match format %r" %
ValueError: time data 'Thu, 30 May 2024 09:00:27 +0000' does not match format '%a, %d %b %Y %H:%M:%S %z'
"GET /feeds/detail/1/ HTTP/1.1" 500 299678
Internal Server Error: /feeds/detail/2/
Traceback (most recent call last):
  File "C:\Users\p-gar\PycharmProjects\ResearchTracker\feeds\templatetags\custom_filters.py", line 28, in format_datetime
    dt = datetime.strptime(value, '%a, %d %b %Y %H:%M:%S %z')
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\_strptime.py", line 554, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\_strptime.py", line 333, in _strptime
    raise ValueError("time data %r does not match format %r" %
ValueError: time data 'Sun, 02 Jun 2024 22:00:02 +0200' does not match format '%a, %d %b %Y %H:%M:%S %z'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\p-gar\PycharmProjects\ResearchTracker\feeds\templatetags\custom_filters.py", line 32, in format_datetime
    dt = datetime.strptime(value, '%Y-%m-%dT%H:%M:%S%z')
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\_strptime.py", line 554, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\_strptime.py", line 333, in _strptime
    raise ValueError("time data %r does not match format %r" %
ValueError: time data 'Sun, 02 Jun 2024 22:00:02 +0200' does not match format '%Y-%m-%dT%H:%M:%S%z'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\p-gar\PycharmProjects\ResearchTracker\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\p-gar\PycharmProjects\ResearchTracker\.venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\p-gar\PycharmProjects\ResearchTracker\.venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\p-gar\PycharmProjects\ResearchTracker\.venv\Lib\site-packages\django\template\response.py", line 92, in rendered_content
    return template.render(context, self._request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\p-gar\PycharmProjects\ResearchTracker\.venv\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\p-gar\PycharmProjects\ResearchTracker\.venv\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\p-gar\PycharmProjects\ResearchTracker\.venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\p-gar\PycharmProjects\ResearchTracker\.venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\p-gar\PycharmProjects\ResearchTracker\.venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\p-gar\PycharmProjects\ResearchTracker\.venv\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\p-gar\PycharmProjects\ResearchTracker\.venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\p-gar\PycharmProjects\ResearchTracker\.venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\p-gar\PycharmProjects\ResearchTracker\.venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\p-gar\PycharmProjects\ResearchTracker\.venv\Lib\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\p-gar\PycharmProjects\ResearchTracker\.venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\p-gar\PycharmProjects\ResearchTracker\.venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\p-gar\PycharmProjects\ResearchTracker\.venv\Lib\site-packages\django\template\defaulttags.py", line 242, in render
    nodelist.append(node.render_annotated(context))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\p-gar\PycharmProjects\ResearchTracker\.venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\p-gar\PycharmProjects\ResearchTracker\.venv\Lib\site-packages\django\template\base.py", line 1059, in render
    output = self.filter_expression.resolve(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\p-gar\PycharmProjects\ResearchTracker\.venv\Lib\site-packages\django\template\base.py", line 737, in resolve
    new_obj = func(obj, *arg_vals)
              ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\p-gar\PycharmProjects\ResearchTracker\feeds\templatetags\custom_filters.py", line 34, in format_datetime
    dt = datetime.strptime(value, '%a, %d %b %Y %H:%M:%S %z')
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\_strptime.py", line 554, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\_strptime.py", line 333, in _strptime
    raise ValueError("time data %r does not match format %r" %
ValueError: time data 'Sun, 02 Jun 2024 22:00:02 +0200' does not match format '%a, %d %b %Y %H:%M:%S %z'
"GET /feeds/detail/2/ HTTP/1.1" 500 298987
